### ISSUE TITLE
VPN Unlimited

### ISSUE THREAD

**Issue by kblaser7** [joshbernfeld/Transmission-Interface-Binder#11]
I am using VPN Unlimited to connect as a VPN client. Can your program be used with this client. I cannot seem to connect while using the client? Or can you help me to bind to this particular client? Thanks!

**Comment by mirfilip** [comment]
I just found this project but, due to lack of response, I think I can.

VPN Unlimited, just like majority of other parties offering VPN, bases its client on `openvpn` software. When you use their client to connect it uses `openvpn` to create or reuse a virtual network interface (often called sth like `utun0`) and uses it to connect to `openvpn` server. You can verify it by connecting and then checking output of `ifconfig` in CLI. 

Transmission has a feature to bind the application networking to particular IP. The problem is, this address usually changes as you reconnect with VPN server (DHCP). This nice project fixes that problem for you as it listens to changes on particular interface and updates binding to IP in Transmission.

So, answering your question: yes, you can use VPN Unlimited client with this program. You can use _any_ VPN client for that matter. Connect to VPN server, note which interface has been used (`ifconfig`) and use this interface name with this tool.

**Comment by joshbernfeld** [comment]
Unfortunately this program can only be used with Transmission since it writes to a preference file which is specific to the Transmission app.
